# Generated by Django 3.0.3 on 2020-02-05 21:49

from django.db import migrations, models
import django.db.models.deletion
import question.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, verbose_name='Code')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Department Name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.CharField(max_length=10, verbose_name='Year')),
                ('semester', models.CharField(choices=[('First', '1'), ('Second', '2')], default='1', max_length=10, verbose_name='Semester')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Height')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Width')),
                ('image', models.ImageField(height_field='height', max_length=500, upload_to=question.models.image_upload_path, verbose_name='Image', width_field='width')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cquestions', to='question.Course', verbose_name='Course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dquestions', to='question.Department', verbose_name='Department')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='question.Department', verbose_name='Department'),
        ),
    ]
