# Generated by Django 3.0.3 on 2020-02-11 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_department'),
        ('question', '0002_auto_20200211_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='user.Department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='question',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dquestions', to='user.Department', verbose_name='Department'),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
