# Generated by Django 3.0.3 on 2020-02-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200211_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='registration_number',
            field=models.CharField(max_length=20, null=True, verbose_name='Registration Number'),
        ),
    ]
